version: "3.8"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    env_file:
      - config/.env
    volumes:
      - postgres-data-squishlink-rs:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data-squishlink-rs:
